proyecto/apps/proyecto_admin/urls.py
from django.conf.urls import patterns, url
from .views import *

urlpatterns = patterns('',
    url(r'^$', inicio, name="url_inicio"),

    url(r'^productos/$', listar_productos, name="url_listar_productos"),
    url(r'^productos/agregar/$', form_agregar_producto, name="url_form_agregar_producto"),
    url(r'^productos/agregar/(?P<id_prod>\d+)/$', form_editar_producto, name="url_form_editar_producto"),
    url(r'^productos/add_1', agregar_productos_p1, name="url_agregar_productos_p1"),
    url(r'^productos/add_2', agregar_productos_p2, name="url_agregar_productos_p2"),
    url(r'^productos/add_3', agregar_productos_p3, name="url_agregar_productos_p3"),
    url(r'^productos/add_4', agregar_productos_p4, name="url_agregar_productos_p4"),
    url(r'^productos/eliminar', eliminar_productos, name="url_eliminar_productos"),
    url(r'^productos/filtrar', filtrar_nombre_producto, name="url_filtrar_nombre_producto"),

    url(r'^productos/categoria/$', listar_categorias_tabla, name="url_listar_categorias_tabla"),
    url(r'^productos/categorias/select', cargar_categorias_select, name="url_cargar_categorias_select"),
    url(r'^productos/categorias/agregar', agregar_categoria, name="url_agregar_categoria"),
    url(r'^productos/categorias/cargar', cargar_categoria, name="url_cargar_categoria"),
    url(r'^productos/categorias/eliminar', eliminar_categoria, name="url_eliminar_categoria"),

    url(r'^productos/marcas/$', listar_marcas, name="url_listar_marcas"),
    url(r'^productos/marcas/agregar', agregar_marca, name="url_agregar_marca"),
    url(r'^productos/marcas/cargar', cargar_marca, name="url_cargar_marca"),
    url(r'^productos/marcas/eliminar', eliminar_marca, name="url_eliminar_marca"),

    url(r'^productos/imagenes/$', listar_imagenes, name="url_listar_imagenes"),
    url(r'^productos/imagenes/eliminar', eliminar_imagenes, name="url_eliminar_imagenes"),
    url(r'^productos/imagenes/cambiar', cambiar_imagenes, name="url_cambiar_imagenes"),
    url(r'^productos/imagenes/subir', subir_nueva_imagen, name="url_subir_nueva_imagen"),

    url(r'^clientes/$', listar_clientes, name="url_listar_clientes"),
    url(r'^clientes/agregar/$', form_agregar_cliente, name="url_form_agregar_cliente"),
    url(r'^clientes/agregar/(?P<id_cli>\d+)/$', form_editar_cliente, name="url_form_editar_cliente"),
    url(r'^clientes/add', agregar_cliente, name="url_agregar_cliente"),
    url(r'^clientes/eliminar', eliminar_clientes, name="url_eliminar_clientes"),
    url(r'^clientes/activar', activar_clientes, name="url_activar_clientes"),
    url(r'^clientes/superusuario', superusuario_cliente, name="url_superusuario_cliente"),
    url(r'^clientes/cambio', cambio_clave_cliente, name="url_cambio_clave_cliente"),

    url(r'^transporte/$', listar_transporte, name="url_listar_transporte"),
    url(r'^transporte/agregar', agregar_transporte, name="url_agregar_transporte"),
    url(r'^transporte/cargar', cargar_transporte, name="url_cargar_transporte"),
    url(r'^transporte/eliminar', eliminar_transporte, name="url_eliminar_transporte"),

    url(r'^impuesto/$', listar_impuestos, name="url_listar_impuestos"),
    url(r'^impuesto/agregar', agregar_impuestos, name="url_agregar_impuestos"),
    url(r'^impuesto/cargar', cargar_impuestos, name="url_cargar_impuestos"),
    url(r'^impuesto/eliminar', eliminar_impuestos, name="url_eliminar_impuestos"),
    url(r'^impuesto/actual', impuesto_actual, name="url_impuesto_actual"),

    url(r'^pedidos/$', listar_pedidos, name="url_listar_pedidos"),
    url(r'^notificaciones/pedidos/$', listar_pedidos_pendientes, name="url_listar_pedidos_pendientes"),
    url(r'^pedidos/(?P<id_ped>\d+)/$', ver_detalle_pedido, name="url_ver_detalle_pedido"),
    url(r'^pedidos/deposito', cargar_deposito, name="url_cargar_deposito"),
    url(r'^pedidos/cliente', cargar_ped_cliente, name="url_cargar_ped_cliente"),
    url(r'^pedidos/estado', cambiar_estado_pedidos, name="url_cambiar_estado_pedidos"),
    url(r'^pedidos/eliminar', eliminar_pedido, name="url_eliminar_pedido"),

    url(r'^tags/', cargar_todos_tags, name="url_cargar_todos_tags"),

    url(r'^consulta/productos/', json_productos, name="url_json_productos"),
)

proyecto/proyecto/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

#Internacionalizacion para javascript
js_info_dict = {
    'domain': 'djangojs',
    'packages': ('wrnpro', ),
}

urlpatterns =patterns ('',
    url(r'^user/', include('apps.users.urls', namespace="users_app")),
    url(r'^', include('apps.portal.urls', namespace="portal_app")),
    url(r'^shop/', include('apps.shop.urls', namespace="shop_app")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dashboard/', include('apps.proyecto_admin.urls', namespace="dashboard_app")),

    # Internacionalizacion
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    url(r'^rosetta/', include('rosetta.urls')),
)
if settings.DEBUG:
    urlpatterns += patterns("",
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT,}
        ),
)

proyecto/templates/dashboard/cliente/administrar.html
{% extends 'dashboard/base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block titulo %}{% trans "BLoom: Administrar clientes" %}{% endblock titulo %}
{% block estilos %}
{% endblock estilos %}

<!--Notificacion de productos por debajo del stock-->
{% block notif_prod_numero %}
    {% if notif_stock|length > 0 %}
        <span class="label label-danger">{{ notif_stock|length }}</span>
    {% endif %}
{% endblock notif_prod_numero %}

{% block notif_prod_mensaje %}
    {% for p in notif_stock%}
        <li>
            <a href="{% url 'dashboard_app:url_form_editar_producto' id_prod=p.pro_id %}">
                <div class="pull-left">
                    <img src="{% if p.pro_imagen_principal %}
                    {% for i in p.pro_imagen_principal %}
                        {{ i.img_data.url }}
                    {% endfor %}
                    {% else %}{% static 'proyecto/dashboard/img/no-imagen.png' %}{% endif %}" class="img-circle" />
                </div>
                <h4 style="padding-bottom:6px; font-weight: 600;">{{ p.pro_nombre|truncatechars:20 }} <span class="label label-danger">{% trans "Stock" %}: {{ p.pro_stock }}</span></h4>
                <p>{% trans "Categoría" %}: {{ p.categorias.cat_nombre}}</p>
            </a>
        </li>
    {% endfor %}
{% endblock notif_prod_mensaje %}

{% block notif_prod_ver %}
    {% if notif_stock %}
        <li class="footer"><a href="{% url 'dashboard_app:url_listar_productos_bajo_stock' %}">{% trans "Ver todas las notificaciones" %}</a></li>
    {% else %}
        <li class="footer"><a href="#">{% trans "Sin notificaciones que mostrar" %}</a></li>
    {% endif %}
{% endblock %}

<!--Notificacion de pedidos pendientes-->
{% block notif_pedido_numero %}
    {% if notif_pedidos|length > 0 %}
        <span class="label label-warning">{{ notif_pedidos|length }}</span>
    {% endif %}
{% endblock notif_pedido_numero %}

{% block notif_pedidos_mensaje %}
    {% for p in notif_pedidos%}
        <li>
            <a href="{% url 'dashboard_app:url_listar_pedidos_pendientes' %}">
                <h4 style="padding-bottom:6px">
                    {% trans "Cód:" %} {{ p.ped_id }} <small>{% trans "Cliente" %}:  {{ p.cliente.us_nombre }} {{ p.cliente.us_apellidos }}</small>
                </h4>
                <p style="padding-bottom:6px">$ {{ p.ped_total_pagar }}
                <span class="label label-{% if p.ped_estado == 'pendiente' %}warning{% else %}info{% endif %}" style="margin-left: 50px; font-size: 12px;">{{ p.ped_estado|capfirst }}</span></p>
            </a>
        </li>
    {% endfor %}
{% endblock notif_pedidos_mensaje %}

{% block notif_pedidos_ver %}
    {% if notif_pedidos %}
        <li class="footer"><a href="{% url 'dashboard_app:url_listar_pedidos_pendientes' %}">{% trans "Ver todas las notificaciones" %}</a></li>
    {% else %}
        <li class="footer"><a href="#">{% trans "Sin notificaciones que mostrar" %}</a></li>
    {% endif %}
{% endblock %}

{% block contenido %}
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header box-header-background with-border">
                        <h3 class="box-title ">{% trans "Administrar clientes" %}</h3>
                    </div>
                    <div class="box-body">
                        <table class="table table-bordered table-striped" id="tabla_clientes">
                            <thead >
                            <tr>
                                {% if user.is_superuser %}<th class="active">{% trans "Superusuario" %}</th>{% endif %}
                                <th class="active">{% trans "Imagen" %}</th>
                                <th class="active">{% trans "Nombre del cliente" %}</th>
                                <th class="active">{% trans "Teléfono" %}</th>
                                <th class="active">{% trans "Email" %}</th>
                                <th class="active">{% trans "Usuario" %}</th>
                                <th class="active">{% trans "Estado" %}</th>
                                <th class="active">{% trans "Acción" %}</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for c in clientes%}
                                <tr class="custom-tr">
                                    {% if user.is_superuser %}
                                    <td style="width: 50px" class="vertical-td">
                                        <input onchange="cli_cambiar_superusuario('{% url "dashboard_app:url_superusuario_cliente" %}?id={{ c.id }}', this)" type="checkbox" {% if c.is_superuser %}checked{% endif %} data-toggle="toggle" data-on="Si" data-off="No" />
                                    </td>
                                    {% endif %}
                                    <td align="center">
                                        <img src="{% if c.us_avatar %}
                                            {{ c.us_avatar.url }}
                                        {% else %}{% static 'proyecto/img/sin-imagen-user.png' %}{% endif %}" style="width: 80px;" />
                                    </td>
                                    <td class="vertical-td">{{ c.us_nombre }} {{ c.us_apellidos }} <strong>{% if c.id == user.id %} ({% trans "Yo" %}){% endif %}</strong></td>
                                    <td class="vertical-td" style="font-size: 17px"><span class="label label-success">{{ c.us_telefono_movil }}</span></td>
                                    <td class="vertical-td"> <a href="mailto:#">{{ c.email }}</a></td>
                                    <td class="vertical-td">{{ c.username }}</td>
                                    <td class="vertical-td">{% if c.is_active%}<span style="font-size: 13px" class="label label-primary">{% trans "Activo" %}</span>{% else %}<span style="font-size: 13px" class="label label-danger">
                                        {% trans "Inactivo" %}</span>{% endif %}</td>
                                    <td class="vertical-td">
                                        <div class="btn-group">
                                            <a href="{% url 'dashboard_app:url_form_editar_cliente' id_cli=c.id %}" class="btn bg-navy btn-xs" title="{% trans 'Editar' %}"><i class="glyphicon glyphicon-edit"></i></a>
                                            {% if c.is_active %}
                                            <button class="btn btn-danger btn-xs" title="{% trans 'Eliminar' %}" onclick="prod_eliminar_objetos('{% url "dashboard_app:url_eliminar_clientes" %}?id={{ c.id }}', 'CL', 'tabla_clientes', this)"><i class="fa fa-trash-o"></i></button>
                                            {% else %}
                                            <button class="btn btn-success btn-xs" title="{% trans 'Activar' %}" onclick="cli_activar_usuario('{% url "dashboard_app:url_activar_clientes" %}?id={{ c.id }}', this)"><i class="fa fa-exchange"></i></button>
                                            {% endif %}
                                            <button class="btn btn-warning btn-xs" title="{% trans 'Cambiar contraseña' %}" onclick="cli_modal_cambiar_clave({{ c.id }})"><i class="fa fa-key"></i></button>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!--Modal ecambiar clave-->
    <div class="modal fade" id="modal_cambiar_clave" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Cerrar</span></button>
                    <h4 class="modal-title" id="myModalLabel" style="font-weight: 600;">{% trans "Cambio de contraseña" %}</h4>
                </div>
                <div class="modal-body">
                    <form role="form" enctype="multipart/form-data" id="formulario_cambio_clave" name="formulario_cambio_clave" method="post" onsubmit="return false">{% csrf_token %}
                        <div class="box-body">
                            <!-- Contraseña actual -->
                            {% trans "Contraseña actual" as i18n_clave_actual %}
                            <div class="form-group">
                                <label>{{ i18n_clave_actual }} <span class="required">*</span></label>
                                <input type="password" id="cli_clave_actual" name="cli_clave_actual" placeholder="{{ i18n_clave_actual }}" class="form-control">
                            </div>
                            <!-- Contraseña nueva 1 -->
                            {% trans "Nueva contraseña" as i18n_clave_nueva1 %}
                            <div class="form-group">
                                <label>{{ i18n_clave_nueva1 }} <span class="required">*</span></label>
                                <input type="password" id="cli_clave_nueva1" name="cli_clave_nueva1" placeholder="{{ i18n_clave_nueva1 }}" class="form-control">
                            </div>
                            <!-- Contraseña nueva 2-->
                            {% trans "Repita la contraseña" as i18n_clave_nueva2 %}
                            <div class="form-group">
                                <label>{{ i18n_clave_nueva2 }} <span class="required">*</span></label>
                                <input type="password" id="cli_clave_nueva2" name="cli_clave_nueva2" placeholder="{{ i18n_clave_nueva2 }}" class="form-control">
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default pull-left" data-dismiss="modal">{% trans "Cancelar" %}</button>
                            <button type="submit" onclick="cli_cambiar_clave('{% url "dashboard_app:url_cambio_clave_cliente" %}')" class="btn bg-olive">{% trans "Cambiar contraseña" %}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock contenido %}

{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function() {
            $('#menu_clientes').addClass("active");
            $('#menu_clientes_administrar').addClass("active");
            $('#menu_clientes_administrar').children('a').removeAttr('href');

            var table = $('#tabla_clientes').DataTable( {
                pageLength: 20,
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'print',
                        exportOptions: {columns: ':visible'}
                    },
                    {
                        extend: 'excel',
                        exportOptions: {columns: ':visible'},
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {columns: ':visible'},
                    },
                    {
                        extend: 'copy',
                        exportOptions: {columns: ':visible'},
                    },
                    'colvis'
                ]
            });

            table.buttons().container().appendTo('#tabla_clientes_wrapper .col-sm-6:eq(0)');
        });
    </script>
{% endblock scripts %}

proyecto/templates/dashboard/cliente/agregar.html
{% extends 'dashboard/base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block titulo %}{% if not proveedor_editar %}{% trans "BLoom: Crear un nuevo cliente" %}{% else %}{% trans "proyecto: Editar cliente" %}{% endif %}{% endblock titulo %}
{% block estilos %}
{% endblock estilos %}

{% block contenido %}
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header box-header-background with-border">
                        <h3 class="box-title ">{% if not proveedor_editar %}{% trans "Crear un nuevo cliente" %}{% else %}{% trans "Editar cliente" %}{% endif %}</h3>
                    </div>
                    <form role="form" enctype="multipart/form-data" id="formulario_agregar_cliente" name="formulario_agregar_cliente" onsubmit="return false;" method="post">{% csrf_token %}
                        {% if cliente_editar %}
                            <br />
                            <div align="center"><a href="{% url 'dashboard_app:url_listar_clientes' %}" class="btn bg-green" >
                                <i class="fa fa-arrow-left" aria-hidden="true"></i> {% trans "Regresar a la lista de clientes" %}</a>
                            </div>
                            <br/>
                        {% endif %}
                        <div class="row">
                            <div class="col-md-6 col-sm-12 col-xs-12 col-md-offset-3">
                                <div class="box-body">
                                    <!-- Usuario y contrasena -->
                                    <div class="row">
                                        {% trans "Usuario" as i18n_cliente_usuario %}
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label>{{ i18n_cliente_usuario }} <span class="required">*</span></label>
                                                <input type="text" id="cliente_usuario" name="cliente_usuario" placeholder="{{ i18n_cliente_usuario }}" value="{{ cliente_editar.0.username}}" class="form-control" maxlength="100" required>
                                            </div>
                                        </div>
                                        {% trans "Contraseña" as i18n_cliente_contrasena %}
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label>{{ i18n_cliente_contrasena }} <span class="required">*</span></label>
                                                {% if cliente_editar.0.password != 1%}
                                                <input type="password" id="cliente_contrasena" name="cliente_contrasena" placeholder="{{ i18n_cliente_contrasena }}" value="{{ cliente_editar.0.password }}" class="form-control" maxlength="10" required>
                                                {% else %}
                                                <h4>{% trans "Cambiarla en Adm. usuarios " %} <i class="fa fa-key"></i></h4>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Nombre -->
                                    {% trans "Nombre" as i18n_cliente_nombre %}
                                    <div class="form-group">
                                        <label>{{ i18n_cliente_nombre }} <span class="required">*</span></label>
                                        <input type="text" id="cliente_nombre" name="cliente_nombre" placeholder="{{ i18n_cliente_nombre }}" value="{{ cliente_editar.0.us_nombre}}" class="form-control" maxlength="100" required>
                                    </div>
                                    <!-- Apellido -->
                                    {% trans "Apellido" as i18n_cliente_apellido %}
                                    <div class="form-group">
                                        <label>{{ i18n_cliente_apellido }} <span class="required">*</span></label>
                                        <input type="text" id="cliente_apellido" name="cliente_apellido" placeholder="{{ i18n_cliente_apellido }}" value="{{ cliente_editar.0.us_apellidos}}" class="form-control" maxlength="100" required>
                                    </div>
                                    <!-- Email -->
                                    {% trans "Correo electrónico" as i18n_cliente_email %}
                                    <div class="form-group">
                                        <label>{{ i18n_cliente_email }} <span class="required">*</span></label>
                                        <input type="text" id="cliente_email" name="cliente_email" placeholder="{{ i18n_cliente_email }}" value="{{ cliente_editar.0.email}}" class="form-control" maxlength="254" required>
                                    </div>
                                    <!-- Telefono/Celular -->
                                    {% trans "Teléfono o celular" as i18n_cliente_telefono %}
                                    <div class="form-group">
                                        <label>{{ i18n_cliente_telefono }} <span class="required">*</span></label>
                                        <input type="text" id="cliente_telefono" name="cliente_telefono" placeholder="{{ i18n_cliente_telefono }}" value="{{ cliente_editar.0.us_telefono_movil}}" class="form-control" maxlength="10" required>
                                    </div>
                                    <!-- Avatar actual -->
                                    <div class="hide form-group">
                                        <label>{% trans "Imagen" %}</label>
                                    </div>
                                    {% if cliente_editar.us_avatar %}
                                    <div class="form-group hide" align="center" id="avatar_usuario_actual">
                                        <div class="fileinput fileinput-new" data-provides="fileinput">
                                            <table border="0">
                                                <tr>
                                                    <td><div class="fileinput-new thumbnail g-logo-img"><img src="{{ cliente_editar.0.us_avatar }}"></div></td>
                                                </tr>
                                                <tr>
                                                    <td><button onclick="cambiar_logo()" id="btn_cambiar_avatar" class="btn btn-block bg-navy">{% trans "Cambiar imagen" %}</button></td>
                                                </tr>
                                            </table>
                                        </div>
                                    </div>
                                    {% endif %}
                                     <!-- Avatar nuevo -->
                                    <div align="center" class="hide form-group" id="avatar_usuario_nuevo" {% if cliente_editar.us_avatar %}style="display: none"{% endif %}>
                                        {% if cliente_editar.0.us_avatar %}
                                        <table border="0">
                                            <tr><td><button onclick="restablecer_logo()" id="btn_restablecer_avatar" class="btn btn-block bg-navy">{% trans "Restablecer imagen" %}</button></td></tr>
                                        </table>
                                        <br>
                                        {% endif %}
                                        <input id="id_avatar_usuario" name="id_avatar_usuario" class="file" accept="image/*" type="file">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="box-footer" align="center">
                            <button onclick="cli_agregar_cliente('{% url "dashboard_app:url_agregar_cliente" %}', '{{ cliente_editar.0.id }}')" id="btn_clientes_agregar" class="btn bg-light-blue" type="submit">{% trans "Guardar cambios" %}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock contenido %}

{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function() {
            $('#menu_clientes').addClass("active");
            $('#menu_clientes_agregar').addClass("active");
            $('#menu_clientes_agregar').children('a').removeAttr('href');
        });

        //Subida de magen
        $("#id_avatar_usuario").fileinput({
            allowedFileExtensions: ["jpg", "jpeg", "png", "gif"],
            removeLabel: "{% trans 'Eliminar' %}",
            browseLabel: "{% trans 'Buscar...' %}",
            maxFileSize: 1024,
            minFileCount: 0,
            maxFileCount: 1,
            showUpload: false
        });

        function cambiar_logo() {
            $("#avatar_usuario_actual").hide();
            $("#avatar_usuario_nuevo").show();
        }

        function restablecer_logo() {
            $("#avatar_usuario_actual").show();
            $("#avatar_usuario_nuevo").hide();
        }
    </script>
{% endblock scripts %}