proyecto/apps/proyecto_admin/urls.py
from django.conf.urls import patterns, url
from .views import *

urlpatterns = patterns('',
    url(r'^$', inicio, name="url_inicio"),

    url(r'^productos/$', listar_productos, name="url_listar_productos"),
    url(r'^productos/agregar/$', form_agregar_producto, name="url_form_agregar_producto"),
    url(r'^productos/agregar/(?P<id_prod>\d+)/$', form_editar_producto, name="url_form_editar_producto"),
    url(r'^productos/add_1', agregar_productos_p1, name="url_agregar_productos_p1"),
    url(r'^productos/add_2', agregar_productos_p2, name="url_agregar_productos_p2"),
    url(r'^productos/add_3', agregar_productos_p3, name="url_agregar_productos_p3"),
    url(r'^productos/add_4', agregar_productos_p4, name="url_agregar_productos_p4"),
    url(r'^productos/eliminar', eliminar_productos, name="url_eliminar_productos"),
    url(r'^productos/filtrar', filtrar_nombre_producto, name="url_filtrar_nombre_producto"),

    url(r'^productos/categoria/$', listar_categorias_tabla, name="url_listar_categorias_tabla"),
    url(r'^productos/categorias/select', cargar_categorias_select, name="url_cargar_categorias_select"),
    url(r'^productos/categorias/agregar', agregar_categoria, name="url_agregar_categoria"),
    url(r'^productos/categorias/cargar', cargar_categoria, name="url_cargar_categoria"),
    url(r'^productos/categorias/eliminar', eliminar_categoria, name="url_eliminar_categoria"),

    url(r'^productos/marcas/$', listar_marcas, name="url_listar_marcas"),
    url(r'^productos/marcas/agregar', agregar_marca, name="url_agregar_marca"),
    url(r'^productos/marcas/cargar', cargar_marca, name="url_cargar_marca"),
    url(r'^productos/marcas/eliminar', eliminar_marca, name="url_eliminar_marca"),

    url(r'^productos/imagenes/$', listar_imagenes, name="url_listar_imagenes"),
    url(r'^productos/imagenes/eliminar', eliminar_imagenes, name="url_eliminar_imagenes"),
    url(r'^productos/imagenes/cambiar', cambiar_imagenes, name="url_cambiar_imagenes"),
    url(r'^productos/imagenes/subir', subir_nueva_imagen, name="url_subir_nueva_imagen"),

    url(r'^clientes/$', listar_clientes, name="url_listar_clientes"),
    url(r'^clientes/agregar/$', form_agregar_cliente, name="url_form_agregar_cliente"),
    url(r'^clientes/agregar/(?P<id_cli>\d+)/$', form_editar_cliente, name="url_form_editar_cliente"),
    url(r'^clientes/add', agregar_cliente, name="url_agregar_cliente"),
    url(r'^clientes/eliminar', eliminar_clientes, name="url_eliminar_clientes"),
    url(r'^clientes/activar', activar_clientes, name="url_activar_clientes"),
    url(r'^clientes/superusuario', superusuario_cliente, name="url_superusuario_cliente"),
    url(r'^clientes/cambio', cambio_clave_cliente, name="url_cambio_clave_cliente"),

    url(r'^transporte/$', listar_transporte, name="url_listar_transporte"),
    url(r'^transporte/agregar', agregar_transporte, name="url_agregar_transporte"),
    url(r'^transporte/cargar', cargar_transporte, name="url_cargar_transporte"),
    url(r'^transporte/eliminar', eliminar_transporte, name="url_eliminar_transporte"),

    url(r'^impuesto/$', listar_impuestos, name="url_listar_impuestos"),
    url(r'^impuesto/agregar', agregar_impuestos, name="url_agregar_impuestos"),
    url(r'^impuesto/cargar', cargar_impuestos, name="url_cargar_impuestos"),
    url(r'^impuesto/eliminar', eliminar_impuestos, name="url_eliminar_impuestos"),
    url(r'^impuesto/actual', impuesto_actual, name="url_impuesto_actual"),

    url(r'^pedidos/$', listar_pedidos, name="url_listar_pedidos"),
    url(r'^notificaciones/pedidos/$', listar_pedidos_pendientes, name="url_listar_pedidos_pendientes"),
    url(r'^pedidos/(?P<id_ped>\d+)/$', ver_detalle_pedido, name="url_ver_detalle_pedido"),
    url(r'^pedidos/deposito', cargar_deposito, name="url_cargar_deposito"),
    url(r'^pedidos/cliente', cargar_ped_cliente, name="url_cargar_ped_cliente"),
    url(r'^pedidos/estado', cambiar_estado_pedidos, name="url_cambiar_estado_pedidos"),
    url(r'^pedidos/eliminar', eliminar_pedido, name="url_eliminar_pedido"),

    url(r'^tags/', cargar_todos_tags, name="url_cargar_todos_tags"),

    url(r'^consulta/productos/', json_productos, name="url_json_productos"),
)

proyecto/proyecto/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

#Internacionalizacion para javascript
js_info_dict = {
    'domain': 'djangojs',
    'packages': ('wrnpro', ),
}

urlpatterns =patterns ('',
    url(r'^user/', include('apps.users.urls', namespace="users_app")),
    url(r'^', include('apps.portal.urls', namespace="portal_app")),
    url(r'^shop/', include('apps.shop.urls', namespace="shop_app")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dashboard/', include('apps.proyecto_admin.urls', namespace="dashboard_app")),

    # Internacionalizacion
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    url(r'^rosetta/', include('rosetta.urls')),
)
if settings.DEBUG:
    urlpatterns += patterns("",
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT,}
        ),
)

proyecto/templates/dashboard/ajustes/categorias.html
{% extends 'dashboard/base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block titulo %}{% trans "BLoom: Categorías de producto" %}{% endblock titulo %}
{% block estilos %}
{% endblock estilos %}


{% block contenido %}
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header box-header-background with-border">
                        <h3 class="box-title ">{% trans "Categorías de producto" %}</h3>
                    </div>
                    <div class="box-background">
                        <form id="formulario_producto_categoria" name="formulario_producto_categoria" role="form" enctype="multipart/form-data" method="post" onsubmit="return false;">{% csrf_token %}
                            <div class="row">
                                <div class="col-md-6 col-sm-12 col-xs-12 col-md-offset-3">
                                    <div class="box-body">
                                        {% trans "Categoría" as i18n_nombre_categoria_producto%}
                                        {% trans "Subcategoría" as i18n_nombre_subcategoria_producto%}
                                        <div id="id_tipo_entrada_ui" class="form-group hide" align="center" style="display: none">
                                            <input id="tipo_entrada" type="checkbox" checked data-toggle="toggle" data-on="{{ i18n_nombre_categoria_producto }}" data-off="{{ i18n_nombre_subcategoria_producto }}" data-onstyle="warning" data-offstyle="info" data-width="110">
                                        </div>
                                        <!-- Categoria -->
                                        {% if categorias %}
                                        {% trans "Seleccione una categoría" as i18n_seleccione_categoria%}
                                        <div id="id_categoria_padre_ui" class="form-group" style="display: none">
                                            <label>{{ i18n_nombre_categoria_producto }}</label>
                                            <select id="id_categoria_padre" name="id_categoria_padre" style="width: 99%;">
                                                <option disabled value="0">{{ i18n_seleccione_categoria }}</option>
                                            </select>
                                        </div>
                                        {% endif %}
                                        <!-- Subcategoria -->
                                        <div class="form-group">
                                            <label id="label_categoria_padre">{{ i18n_nombre_categoria_producto }} </label><span class="required">*</span>
                                            <input id="id_categoria_hijo" name="id_categoria_hijo" type="text" placeholder="{{ i18n_nombre_categoria_producto }}" class="form-control" maxlength="30" required>
                                        </div>
                                        <!-- Descripcion-->
                                        {% trans "Descripción" as i18n_categoria_descripcion %}
                                        <div class="form-group">
                                            <label>{{ i18n_categoria_descripcion }}</label>
                                            <textarea style="resize: none; height: 90px" id="categoria_descripcion" name="categoria_descripcion" class="form-control autogrow" placeholder="{{ i18n_categoria_descripcion }}"></textarea>
                                        </div>
                                        <button onclick="ajus_agregar_categoria('{% url "dashboard_app:url_agregar_categoria" %}')" id="btn_guardar_categoria" type="submit" class="btn bg-light-blue">{% trans "Guardar" %}</button>
                                        <button type="button" onclick="ajus_cancelar_categoria()" class="btn btn-default">{% trans "Cancelar" %}</button><br/><br/><br/><br/>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="box-footer"></div>
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <!-- Tabla -->
                            <table class="table table-bordered table-striped" id="tabla_categorias" cellspacing="0" width="100%">
                                <thead >
                                    <tr>
                                        <th class="active" style="width: 35px;">{% trans "Cód." %}</th>
                                        <th class="active">{% trans "Nombre de la categoría" %}</th>
                                        <th class="active" style="width: 50px;">{% trans "Acción" %}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for c in categorias %}
                                    <tr class="custom-tr">
                                        <td class="vertical-td">{{ c.cat_id }}</td>
                                        <td class="vertical-td">{{ c.cat_nombre }} {% if c.cat_id_padre_id > 0 %}, <span class="label label-waring"> {{ c.cat_id_padre.cat_nombre}}</span>{% endif %}</td>
                                        <td class="vertical-td">
                                            <div class="btn-group">
                                                <button onclick="ajus_cargar_categoria('{% url "dashboard_app:url_cargar_categoria" %}?id={{ c.cat_id }}', this)" class="btn bg-navy btn-xs" title="{% trans 'Editar' %}"><i class="glyphicon glyphicon-edit"></i></button>
                                                <button onclick="prod_eliminar_objetos('{% url "dashboard_app:url_eliminar_categoria" %}?id={{ c.cat_id }}', 'CC', 'tabla_categorias', this)" class="btn btn-danger btn-xs" title="{% trans 'Eliminar' %}"><i class="fa fa-trash-o"></i></button>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock contenido %}

{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function() {
            {% if categorias %}
                cargar_productos_select("{% url 'dashboard_app:url_cargar_categorias_select' %}", "{{ i18n_seleccione_categoria }}", "id_categoria_padre");
                $("#id_tipo_entrada_ui").show();
                $("#id_categoria_padre").val("0");
                $("#id_categoria_padre").select2({ selected: "0" });
            {% endif %}

            $('#menu_ajustes').addClass("active");
            $('#menu_ajustes_categorias').addClass("active");
            $('#menu_ajustes_categorias_administrar').addClass("active");
            $('#menu_ajustes_categorias_administrar').children('a').removeAttr('href');

            var table = $('#tabla_categorias').DataTable({
                lengthChange: false
            });

            //Toggle categoria-subcategoria
            $('#tipo_entrada').change(function() {
                if($(this).prop('checked') == true){
                    $('#id_categoria_padre_ui').hide();
                    $("#label_categoria_padre").text("Categoría");
                    $("#id_categoria_hijo").attr("placeholder", $("#label_categoria_padre").text())
                }else{
                    $('#id_categoria_padre_ui').show();
                    $("#label_categoria_padre").text("Sub-categoría");
                    $("#id_categoria_hijo").attr("placeholder", $("#label_categoria_padre").text())
                }
            });

            $("#menu_ajustes_categorias").data("test", {categoria_id: ""});
        });
    </script>
{% endblock scripts %}

proyecto/templates/dashboard/ajustes/notif_pedidos.html
{% extends 'dashboard/base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block titulo %}{% trans "BLoom: Notificación de pedidos" %}{% endblock titulo %}
{% block estilos %}
{% endblock estilos %}

<!--Notificacion de productos por debajo del stock-->
{% block notif_prod_numero %}
    {% if notif_stock|length > 0 %}
        <span class="label label-danger">{{ notif_stock|length }}</span>
    {% endif %}
{% endblock notif_prod_numero %}

{% block notif_prod_mensaje %}
    {% for p in notif_stock%}
        <li>
            <a href="{% url 'dashboard_app:url_form_editar_producto' id_prod=p.pro_id %}">
                <div class="pull-left">
                    <img src="{% if p.pro_imagen_principal %}
                    {% for i in p.pro_imagen_principal %}
                        {{ i.img_data.url }}
                    {% endfor %}
                    {% else %}{% static 'proyecto/dashboard/img/no-imagen.png' %}{% endif %}" class="img-circle" />
                </div>
                <h4 style="padding-bottom:6px; font-weight: 600;">{{ p.pro_nombre|truncatechars:20 }} <span class="label label-danger">{% trans "Stock" %}: {{ p.pro_stock }}</span></h4>
                <p>{% trans "Categoría" %}: {{ p.categorias.cat_nombre}}</p>
            </a>
        </li>
    {% endfor %}
{% endblock notif_prod_mensaje %}

{% block notif_prod_ver %}
    {% if notif_stock %}
        <li class="footer"><a href="{% url 'dashboard_app:url_listar_productos_bajo_stock' %}">{% trans "Ver todas las notificaciones" %}</a></li>
    {% else %}
        <li class="footer"><a href="#">{% trans "Sin notificaciones que mostrar" %}</a></li>
    {% endif %}
{% endblock %}

<!--Notificacion de pedidos pendientes-->
{% block notif_pedidos_ver %}
    <li class="footer"><a href="#">{% trans "Sin notificaciones que mostrar" %}</a></li>
{% endblock %}

{% block contenido %}
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header box-header-background with-border">
                        <h3 class="box-title ">{% trans "Pedidos a proyecto" %}</h3>
                        <div class="box-tools pull-right">
                            <div class="box-tools">
                                <div class="btn-group" role="group">
                                    <select style="height: 30px" id="id_filtrar_pedido" class="form-control" onclick="filtrar_pedidos('tabla_notificaciones_pedidos','id_filtrar_pedido')">
                                        <option selected value="">{% trans "Todos" %}</option>
                                        <option value="pendiente">{% trans "Pendiente" %}</option>
                                        <option value="verificacion">{% trans "En verificación" %}</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-body">
                        <table class="table table-bordered table-striped" id="tabla_notificaciones_pedidos">
                            <thead >
                            <tr>
                                <th class="active">{% trans "Cód." %}</th>
                                <th class="active">{% trans "Fecha de pedido" %}</th>
                                <th class="active">{% trans "Estado" %}</th>
                                <th class="active">{% trans "Total" %}</th>
                                <th class="active">{% trans "Cliente" %}</th>
                                <th class="active">{% trans "Transporte" %}</th>
                                <th class="active">{% trans "Acción" %}</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for p in notif_pedidos %}
                                <tr class="custom-tr">
                                    <td class="vertical-td">PED-{{ p.ped_id }}</td>
                                    <td class="vertical-td">{{ p.ped_fecha_pedido }}</td>
                                    <td class="vertical-td"><span class="label label-{% if p.ped_estado == 'verificacion' %}info{% else %}warning{% endif %}">{{ p.ped_estado|upper }}</span></td>
                                    <td class="vertical-td currency">$ {{ p.ped_total_pagar }}</td>
                                    <td class="vertical-td">{{ p.cliente.us_nombre }} {{ p.cliente.us_apellidos }}</td>
                                    <td class="vertical-td">{% if p.trans_id %}{{ p.trans_nombre }}{% else %}{% trans "En el local" %}{% endif %}</td>
                                    <td class="vertical-td">
                                        <div class="btn-group">
                                            <a target="_blank" href="{% url 'dashboard_app:url_ver_detalle_pedido' id_ped=p.ped_id %}" title="{% trans 'Ver detalles' %}" class="btn btn-success btn-xs"><i class="glyphicon glyphicon-search"></i></a>
                                            {% if p.ped_imagen_deposito != None%}
                                            <button onclick="abrir_modal_estado_pedido('{% url "dashboard_app:url_cargar_deposito" %}?id={{ p.ped_id }}', this)" title="{% trans 'Cambiar estado' %}" class="btn bg-navy btn-xs"><i class="glyphicon glyphicon-edit"></i></button>
                                            {% else %}
                                            <a class="btn bg-navy btn-xs" disabled="" title="No existe deposito">Fd</a>
                                            {% endif %}
                                            <button onclick="abrir_modal_datos_cliente('{% url "dashboard_app:url_cargar_ped_cliente" %}?id={{ p.ped_id }}')" title="{% trans 'Datos del cliente' %}" class="btn btn-primary btn-xs"><i class="glyphicon glyphicon-user"></i></button>
                                            <button onclick="prod_eliminar_objetos('{% url "dashboard_app:url_eliminar_pedido" %}?id={{ p.ped_id }}', 'PE', 'tabla_notificaciones_pedidos', this)" title="{% trans 'Eliminar pedido' %}" class="btn btn-danger btn-xs"><i class="fa fa-times"></i></button>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock contenido %}

{% block scripts %}
<script src="{% static 'proyecto/dashboard/plugins/eventos/objetos.js' %}"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            $('#menu_ajustes').addClass("active");
            $('#menu_ajustes_notificaciones').addClass("active");
            $('#menu_ajustes_notificaciones_pedidos').addClass("active");
            $('#menu_ajustes_notificaciones_pedidos').children('a').removeAttr('href');

            var table = $('#tabla_notificaciones_pedidos').DataTable( {
                pageLength: 15,
                dom: 'Bfrtip',
                bSort: false,
                buttons: [
                    {
                        extend: 'print',
                        exportOptions: {columns: ':visible'}
                    },
                    {
                        extend: 'excel',
                        exportOptions: {columns: ':visible'}
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {columns: ':visible'}
                    },
                    {
                        extend: 'copy',
                        exportOptions: {columns: ':visible'}
                    },
                    'colvis'
                ]
            } );
        });
    </script>
{% endblock scripts %}

proyecto/templates/dashboard/ajustes/transporte.html
{% extends 'dashboard/base.html' %}
{% load i18n %}
{% load staticfiles %}

{% block titulo %}{% trans "BLoom: Empresas de transporte" %}{% endblock titulo %}
{% block estilos %}
{% endblock estilos %}

<!--Notificacion de productos por debajo del stock-->
{% block notif_prod_numero %}
    {% if notif_stock|length > 0 %}
        <span class="label label-danger">{{ notif_stock|length }}</span>
    {% endif %}
{% endblock notif_prod_numero %}

{% block notif_prod_mensaje %}
    {% for p in notif_stock%}
        <li>
            <a href="{% url 'dashboard_app:url_form_editar_producto' id_prod=p.pro_id %}">
                <div class="pull-left">
                    <img src="{% if p.pro_imagen_principal %}
                    {% for i in p.pro_imagen_principal %}
                        {{ i.img_data.url }}
                    {% endfor %}
                    {% else %}{% static 'proyecto/dashboard/img/no-imagen.png' %}{% endif %}" class="img-circle" />
                </div>
                <h4 style="padding-bottom:6px; font-weight: 600;">{{ p.pro_nombre|truncatechars:20 }} <span class="label label-danger">{% trans "Stock" %}: {{ p.pro_stock }}</span></h4>
                <p>{% trans "Categoría" %}: {{ p.categorias.cat_nombre}}</p>
            </a>
        </li>
    {% endfor %}
{% endblock notif_prod_mensaje %}

{% block notif_prod_ver %}
    {% if notif_stock %}
        <li class="footer"><a href="{% url 'dashboard_app:url_listar_productos_bajo_stock' %}">{% trans "Ver todas las notificaciones" %}</a></li>
    {% else %}
        <li class="footer"><a href="#">{% trans "Sin notificaciones que mostrar" %}</a></li>
    {% endif %}
{% endblock %}

<!--Notificacion de pedidos pendientes-->
{% block notif_pedido_numero %}
    {% if notif_pedidos|length > 0 %}
        <span class="label label-warning">{{ notif_pedidos|length }}</span>
    {% endif %}
{% endblock notif_pedido_numero %}

{% block notif_pedidos_mensaje %}
    {% for p in notif_pedidos%}
        <li>
            <a href="{% url 'dashboard_app:url_listar_pedidos_pendientes' %}">
                <h4 style="padding-bottom:6px">
                    {% trans "Cód:" %} {{ p.ped_id }} <small>{% trans "Cliente" %}:  {{ p.cliente.us_nombre }} {{ p.cliente.us_apellidos }}</small>
                </h4>
                <p style="padding-bottom:6px">$ {{ p.ped_total_pagar }}
                <span class="label label-{% if p.ped_estado == 'pendiente' %}warning{% else %}info{% endif %}" style="margin-left: 50px; font-size: 12px;">{{ p.ped_estado|capfirst }}</span></p>
            </a>
        </li>
    {% endfor %}
{% endblock notif_pedidos_mensaje %}

{% block notif_pedidos_ver %}
    {% if notif_pedidos %}
        <li class="footer"><a href="{% url 'dashboard_app:url_listar_pedidos_pendientes' %}">{% trans "Ver todas las notificaciones" %}</a></li>
    {% else %}
        <li class="footer"><a href="#">{% trans "Sin notificaciones que mostrar" %}</a></li>
    {% endif %}
{% endblock %}

{% block contenido %}
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header box-header-background with-border">
                        <h3 class="box-title ">{% trans "Empresas de transporte" %}</h3>
                    </div>
                    <div class="box-background">
                        <form id="formulario_ajustes_transporte" name="formulario_ajustes_transporte" role="form" enctype="multipart/form-data" method="post" onsubmit="return false;">{% csrf_token %}
                            <div class="row">
                                <div class="col-md-6 col-sm-12 col-xs-12 col-md-offset-3">
                                    <div class="box-body">
                                        {% trans "Nombre de la empresa" as i18n_nombre_transporte%}
                                        <!-- Nombre -->
                                        <div class="form-group">
                                            <label>{{ i18n_nombre_transporte }} </label><span class="required">*</span>
                                            <input id="ajustes_transporte_nombre" name="ajustes_transporte_nombre" type="text" placeholder="{{ i18n_nombre_transporte }}" class="form-control" maxlength="50" required>
                                        </div>
                                        {% trans "Costo de envío" as i18n_costo%}
                                        <!-- Costo -->
                                        <div class="form-group">
                                            <label>{{ i18n_costo }} </label><span class="required">*</span>
                                            <input id="ajustes_transporte_costo" name="ajustes_transporte_costo" type="text" placeholder="{{ i18n_costo }}" class="form-control" required>
                                        </div>
                                        {% trans "Dirección URL" as i18n_url%}
                                        <!-- Url -->
                                        <div class="form-group">
                                            <label>{{ i18n_url }} </label><span class="required">*</span>
                                            <input id="ajustes_transporte_url" name="ajustes_transporte_url" type="text" placeholder="{{ i18n_url }}" class="form-control" maxlength="50" required>
                                        </div>
                                        <button id="btn_guardar_transporte" type="submit" onclick="ajus_agregar_transporte('{% url "dashboard_app:url_agregar_transporte" %}')" class="btn bg-light-blue">{% trans "Guardar" %}</button>
                                        <button type="button" onclick="ajus_cancelar_accion()" class="btn btn-default">{% trans "Cancelar" %}</button><br/><br/>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="box-footer"></div>
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <!-- Tabla -->
                            <table class="table table-bordered table-striped" id="tabla_transporte" cellspacing="0" width="100%">
                                <thead >
                                    <tr>
                                        <th class="active">{% trans "Nombre de la empresa de transporte" %}</th>
                                        <th class="active">{% trans "Costo" %}</th>
                                        <th class="active">{% trans "Dirección URL" %}</th>
                                        <th class="active" style="width: 50px;">{% trans "Acción" %}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for t in transporte %}
                                    <tr class="custom-tr">
                                        <td class="vertical-td">{{ t.trans_nombre }}</td>
                                        <td class="vertical-td">$ {{ t.trans_costo }}</td>
                                        <td class="vertical-td">{{ t.trans_url }}</td>
                                        <td class="vertical-td">
                                            <div class="btn-group">
                                                <button class="btn bg-navy btn-xs" title="{% trans 'Editar' %}" onclick="ajus_cargar_transporte('{% url "dashboard_app:url_cargar_transporte" %}?id={{ t.trans_id }}', this)"><i class="glyphicon glyphicon-edit"></i></button>
                                                <button class="btn btn-danger btn-xs" title="{% trans 'Eliminar' %}" onclick="prod_eliminar_objetos('{% url "dashboard_app:url_eliminar_transporte" %}?id={{ t.trans_id }}', 'TT', 'tabla_transporte', this)"><i class="fa fa-trash-o"></i></button>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock contenido %}

{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function() {
            $('#menu_ajustes').addClass("active");
            $('#menu_ajustes_transporte').addClass("active");
            $('#menu_ajustes_transporte').children('a').removeAttr('href');

            var table = $('#tabla_transporte').DataTable( {
                lengthChange: false
            });

            $("#menu_ajustes_transporte").data("test", {transporte_id: ""});
        });
    </script>
{% endblock scripts %}